import style from "./layout.module.css";
import "@/app/globals.css";
import Image from "next/image";

import logo from "@/public/Logo-White.png";

import { Inter } from "next/font/google";

import SideBar from "@/components/SideBar";
import { auth } from "@/auth";

import MobilBlocker from "@/components/MobilBlocker";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "900", "700", "800", "500"],
  style: ["italic", "normal"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata = {
  title: "ManageStock | Dashboard",
  description: "Generated by create next app",
};

export default async function DashboardLayout({ children }) {
  const session = await auth();
  return (
    <html lang="fr" className={`${inter.variable}`}>
      <body className={style.body}>
        <MobilBlocker />
        <div className={style.bar}>
          <Image src={logo} alt="logo de ManageStock" />
        </div>
        <main className={style.main}>{children}</main>
        <SideBar session={session} />
      </body>
    </html>
  );
}
